// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/telemetry/ports.go

// Package telemetry is a generated GoMock package.
package telemetry

import (
	context "context"
	reflect "reflect"
	telemetry "telemetry-collector/internal/domain/telemetry"

	gomock "github.com/golang/mock/gomock"
)

// MockTelemetryRepository is a mock of TelemetryRepository interface.
type MockTelemetryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryRepositoryMockRecorder
}

// MockTelemetryRepositoryMockRecorder is the mock recorder for MockTelemetryRepository.
type MockTelemetryRepositoryMockRecorder struct {
	mock *MockTelemetryRepository
}

// NewMockTelemetryRepository creates a new mock instance.
func NewMockTelemetryRepository(ctrl *gomock.Controller) *MockTelemetryRepository {
	mock := &MockTelemetryRepository{ctrl: ctrl}
	mock.recorder = &MockTelemetryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryRepository) EXPECT() *MockTelemetryRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockTelemetryRepository) Save(ctx context.Context, t telemetry.Telemetry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockTelemetryRepositoryMockRecorder) Save(ctx, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTelemetryRepository)(nil).Save), ctx, t)
}

// MockDLQPublisher is a mock of DLQPublisher interface.
type MockDLQPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockDLQPublisherMockRecorder
}

// MockDLQPublisherMockRecorder is the mock recorder for MockDLQPublisher.
type MockDLQPublisherMockRecorder struct {
	mock *MockDLQPublisher
}

// NewMockDLQPublisher creates a new mock instance.
func NewMockDLQPublisher(ctrl *gomock.Controller) *MockDLQPublisher {
	mock := &MockDLQPublisher{ctrl: ctrl}
	mock.recorder = &MockDLQPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDLQPublisher) EXPECT() *MockDLQPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockDLQPublisher) Publish(ctx context.Context, payload []byte, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, payload, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockDLQPublisherMockRecorder) Publish(ctx, payload, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockDLQPublisher)(nil).Publish), ctx, payload, reason)
}
