// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapters/inbound/queue/types.go

// Package queue is a generated GoMock package.
package queue

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockQueueMessage is a mock of Message interface.
type MockQueueMessage struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMessageMockRecorder
}

// MockQueueMessageMockRecorder is the mock recorder for MockQueueMessage.
type MockQueueMessageMockRecorder struct {
	mock *MockQueueMessage
}

// NewMockQueueMessage creates a new mock instance.
func NewMockQueueMessage(ctrl *gomock.Controller) *MockQueueMessage {
	mock := &MockQueueMessage{ctrl: ctrl}
	mock.recorder = &MockQueueMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueMessage) EXPECT() *MockQueueMessageMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockQueueMessage) Ack(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockQueueMessageMockRecorder) Ack(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockQueueMessage)(nil).Ack), ctx)
}

// Body mocks base method.
func (m *MockQueueMessage) Body() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Body")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Body indicates an expected call of Body.
func (mr *MockQueueMessageMockRecorder) Body() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Body", reflect.TypeOf((*MockQueueMessage)(nil).Body))
}

// Reject mocks base method.
func (m *MockQueueMessage) Reject(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reject indicates an expected call of Reject.
func (mr *MockQueueMessageMockRecorder) Reject(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockQueueMessage)(nil).Reject), ctx)
}

// Retry mocks base method.
func (m *MockQueueMessage) Retry(ctx context.Context, delay time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retry", ctx, delay)
	ret0, _ := ret[0].(error)
	return ret0
}

// Retry indicates an expected call of Retry.
func (mr *MockQueueMessageMockRecorder) Retry(ctx, delay interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retry", reflect.TypeOf((*MockQueueMessage)(nil).Retry), ctx, delay)
}

// MockQueueClient is a mock of Client interface.
type MockQueueClient struct {
	ctrl     *gomock.Controller
	recorder *MockQueueClientMockRecorder
}

// MockQueueClientMockRecorder is the mock recorder for MockQueueClient.
type MockQueueClientMockRecorder struct {
	mock *MockQueueClient
}

// NewMockQueueClient creates a new mock instance.
func NewMockQueueClient(ctrl *gomock.Controller) *MockQueueClient {
	mock := &MockQueueClient{ctrl: ctrl}
	mock.recorder = &MockQueueClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueClient) EXPECT() *MockQueueClientMockRecorder {
	return m.recorder
}

// Pull mocks base method.
func (m *MockQueueClient) Pull(ctx context.Context, batchSize int) ([]Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, batchSize)
	ret0, _ := ret[0].([]Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockQueueClientMockRecorder) Pull(ctx, batchSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockQueueClient)(nil).Pull), ctx, batchSize)
}
