apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telemetry-collector.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "telemetry-collector.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "telemetry-collector.name" . }}
    spec:
      containers:
        - name: collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_DSN
              value: {{ .Values.env.postgresDsn | quote }}
            - name: WORKER_COUNT
              value: {{ .Values.env.workerCount | quote }}
            - name: QUEUE_BATCH_SIZE
              value: {{ .Values.env.queueBatchSize | quote }}
            - name: POLL_INTERVAL
              value: {{ .Values.env.pollInterval | quote }}
            - name: QUEUE_BACKEND
              value: {{ .Values.env.queueBackend | quote }}
            - name: MQ_GRPC_ADDR
              value: {{ .Values.env.mqGrpcAddr | quote }}
            - name: MQ_TOPIC
              value: {{ .Values.env.mqTopic | quote }}
            - name: MQ_GROUP
              value: {{ .Values.env.mqGroup | quote }}
            - name: MQ_HEARTBEAT_INTERVAL
              value: {{ .Values.env.mqHeartbeatInterval | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
